version: "3.7"

volumes:
  database:

networks:
  backend:
  database:

services:
  # Postgresql database
  db:
    image: postgres:14.2-bullseye
    container_name: ${PROJ_NAME}_db
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - database

  # Django backend
  django:
    env_file: .env
    build:
      context: .
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    image: ${PROJ_NAME}_backend:${IMG_VERSION}
    volumes:
      - .:/app
    container_name: ${PROJ_NAME}_backend_${IMG_VERSION}
    command: bash -c "sleep 5 && sh run.sh"
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - backend
      - database
